language: python
python:
# coverage is breaking for 3.2
#- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev" # development branch
- "nightly"
# install dependencies
install:
- pip install coveralls
# run tests
script: 
- make coverage
after_success: 
- coveralls

