language: python
python:
# coverage is breaking for 3.2
#- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev" # development branch
- "nightly"
# install dependencies
install:
- pip install coveralls
- pip install miniupnpc
# run tests
script: 
- make coverage
after_success: 
- coveralls
after_failure:
- PROJECTPATH=$(pwd)
- cat "$PROJECTPATH/udpserver_test.log"
- cat "$PROJECTPATH/udpserver.log"
- cat "$PROJECTPATH/udpclient.log"
- cat "$PROJECTPATH/udpsocket.log"
- cat "$PROJECTPATH/engine_test.log"
- cat "$PROJECTPATH/engine.log"
