language: python
python:
# coverage is breaking for 3.2
#- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.5-dev" # development branch
- "nightly"
# install dependencies
install:
- pip install coveralls
- pip install miniupnpc
# run tests
script: 
- make coverage
after_success: 
- coveralls
after_failure:
- cat /home/travis/builds/ryutaroikeda/triplepong/udpserver_test.log
- cat /home/travis/builds/ryutaroikeda/triplepong/udpserver.log
- cat /home/travis/builds/ryutaroikeda/triplepong/udpclient.log
- cat /home/travis/builds/ryutaroikeda/triplepong/udpsocket.log
- cat /home/travis/builds/ryutaroikeda/triplepong/engine_test.log
- cat /home/travis/builds/ryutaroikeda/triplepong/engine.log
